language: ruby

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/docker-in-travis/master/scripts/start_docker.sh)

script:
- bundle exec rspec

after_failure: cat docker_daemon.log
